catalog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Home, CategoryView, ServiceView, CategoryNew

urlpatterns = [
    path('', Home.as_view() , name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('categories/', CategoryView.as_view(), name='category_list'),
    path('categories/new', CategoryNew.as_view(), name='category_new'),
    path('services/', ServiceView.as_view(), name='service_list'),
]

software1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include(('catalog.urls','catalog'), namespace='catalog')),
]

catalog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(
        max_length=50, 
        unique=True,  
        help_text='Category Name'
    )
    description = models.TextField(blank=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self):
        self.name = self.name.upper()
        super(Category, self).save()

    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.CharField(
        max_length=50, 
        unique=True,  
        help_text='Service Name'
    )
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Services'

    def save(self):
        self.name = self.name.upper()
        super(Service, self).save()

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms

from .models import Category, Service

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'status']
        labels = {'name': 'Nombre', 'description': 'Descripción', 'status': 'Estado'}
        widget = {'description':forms.TextInput, 'status':forms.CheckboxInput}
         
    def __init__(self, *args, **kwargs ):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
            self.fields['status'].widget.attrs.update({'class':'form-check-input'})

catalog/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from .models import Category, Service
from .forms import CategoryForm

# Create your views here.

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'index.html'
    login_url = '/login'

class CategoryView(LoginRequiredMixin, generic.ListView):
    model = Category
    template_name = 'catalog/category_list.html'
    context_object_name = 'obj'
    login_url = 'login'

class CategoryNew(LoginRequiredMixin, generic.CreateView):
    model = Category
    template_name = 'catalog/category_form.html'
    context_object_name = 'obj'
    form_class = CategoryForm
    success_url = reverse_lazy('catalog:category_list')
    login_url = 'login'


class ServiceView(LoginRequiredMixin, generic.ListView):
    model = Service
    template_name = 'catalog/service_list.html'
    context_object_name = 'obj'
    login_url = 'login'

catalog/templates/catalog/category_form.html
<div class="modal-dialog">
    {% if obj %}
    <form method="POST" role="form" action="">
    {% else %}
    <form method="POST" role="form" action="{% url 'catalog:category_new' %}">
    {% endif %}
        {% csrf_token %}
        <div class="modal-content">
            <div class="modal-header align-items-center p3 p-md-5">
                <h2 class="modal-title" id="exampleModalGridTitle">
                    {% if obj %} Editar {% else %} Nueva {% endif %} Categoria
                </h2>
            </div>
            <div class="modal-body p3 p-md-5">
                <h3 class="h5 mb-5">Información de Unidad de medida</h3>

                {{ form.as_p }}

                <div class="form-check">
                    {{ form.estado }}
                    <label class="form-check-label" for="id_estado">Activo</label>
                </div>
            </div>
            <hr>
            <div class="text-center mb-4">
                <a href="#" rel="modal:close" class="btn btn-danger">Close</a>
                <button type="submit" class="btn btn-primary  btn-pill"> Guardar </button>
            </div>
        </div>
    </form>
</div>

catalog/templates/catalog/category_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<div class="section mt-5">
    <div class="container">
        <div class="mb-3">
            <h2>Categorias</h2>
            <!-- Link to open the modal -->
            <a href="{% url 'catalog:category_new' %}" rel="modal:open" class="btn btn-primary btn-pill">Nuevo</a>
            <input type="search" name="search" id="id_search" placeholder="Buscar..">
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Estado</th>
                        <th>Editar</th>
                        <th>Excluir</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.description }}</td>
                        <td>{{ item.status }}</td>
                        <td><a href="">Editar</a></td>
                        <td><a href="">Excluir</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>  
</div>
{% endblock %}

{% block footer %}
{% endblock %}

catalog/templates/catalog/service_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<div class="section mt-5">
    <div class="container">
        <div class="mb-3">
            <h2>Servicios</h2>
            <button>Nuevo</button>
            <input type="search" name="search" id="id_search" placeholder="Buscar..">
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Editar</th>
                        <th>Excluir</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.status }}</td>
                        <td><a href="">Editar</a></td>
                        <td><a href="">Excluir</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>  
</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="Untree.co" />
    <link rel="shortcut icon" href="favicon.png" />

    <meta name="description" content="" />
    <meta name="keywords" content="bootstrap, bootstrap5" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}" />

    <link rel="stylesheet" href="{% static 'css/tiny-slider.css' %} " />
    <link rel="stylesheet" href="{% static 'css/aos.css' %} " />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- Remember to include jQuery :) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

    <!-- jQuery Modal -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />

    <title>
      Ventas y Alquileres de Inmuebles - Inmobiliaria
    </title>
  </head>
  <body>
    
    {% block navbar %}
      {% include 'navbar.html' %}  
    {% endblock navbar %}
      
    {% block content %}     
    {% endblock content %}
      
    {% block footer %}
      {% include 'footer.html' %}
    {% endblock footer %}
    
    <!-- Modal -->

  <div class="modal fade" id="popup">
  </div>

  {% block control_modal %}
  <script>
    function abrir_modal(url){
      $("#popup").load(url, function(){
        $(this).modal({
          backdrop: 'static',
          keyboard: false
        });
        $(this).modal('show');
      });
      return false;
    }
    
    function cerrar_modal(){
      $(this).modal('hide');
      return false;
    }
  </script>
  {% endblock %}


    <!-- Preloader -->
    <div id="overlayer"></div>
    <div class="loader">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/tiny-slider.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/counter.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
    
  </body>
</html>

templates/footer.html
<div class="site-footer">
  <div class="container">
    
    <div class="row">
      <div class="text-center">
        <div class="widget">
          <ul class="list-unstyled social text-center">
            <li>
              <a href="#"><span class="icon-instagram"></span></a>
            </li>
            <li>
              <a href="#"><span class="icon-twitter"></span></a>
            </li>
            <li>
              <a href="#"><span class="icon-facebook"></span></a>
            </li>
            <li>
              <a href="#"><span class="icon-linkedin"></span></a>
            </li>
            <li>
              <a href="#"><span class="icon-pinterest"></span></a>
            </li>
            <li>
              <a href="#"><span class="icon-dribbble"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- /.row -->

    <div class="row mt-2">
      <div class="col-12 text-center">
        <!-- 
            **==========
            NOTE: 
            Please don't remove this copyright link unless you buy the license here https://untree.co/license/  
            **==========
          -->
        <p>
          Copyright &copy;
          <script>
            document.write(new Date().getFullYear());
          </script>
          . All Rights Reserved. &mdash; Designed with love by
          <a href="https://untree.co">Untree.co</a>
          <!-- License information: https://untree.co/license/ -->
        </p>
        <div>
          Distributed by
          <a href="https://themewagon.com/" target="_blank">themewagon</a>
        </div>
      </div>
    </div>

  </div>
  <!-- /.container -->
</div>
<!-- /.site-footer -->

templates/hero.html
<div class="hero">
    <div class="hero-slide">
        <div class="img overlay" style="background-image: url('images/hero_bg_3.jpg')"></div>
        <div class="img overlay" style="background-image: url('images/hero_bg_2.jpg')"></div>
        <div class="img overlay" style="background-image: url('images/hero_bg_1.jpg')"></div>
    </div>

    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-9 text-center">
                <h1 class="heading" data-aos="fade-up">
                    La forma más fácil de encontrar la casa de sus sueños
                </h1>
                <form action="#" class="narrow-w form-search d-flex align-items-stretch mb-3" data-aos="fade-up"
                    data-aos-delay="200">
                    <input type="text" class="form-control px-4" placeholder="Su ciudad, barrio, calle" />
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}" />
    <title>Iniciar Sesión</title>
    
</head>
<body class="text-center mt-5">
  <div class="container">
    <div class="text-center">
      <div class="card">
        <div class="card-header">
          Iniciar Sesión
        </div>
        <div class="card-body">
          <form class="form-signin" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Iniciar</button>
          </form>
        </div>
        <div class="card-footer">
          <p class="text-muted">© 2022</p>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

templates/navbar.html
<div class="site-mobile-menu site-navbar-target">
  <div class="site-mobile-menu-header">
    <div class="site-mobile-menu-close">
      <span class="icofont-close js-menu-toggle"></span>
    </div>
  </div>
  <div class="site-mobile-menu-body"></div>
</div>

<nav class="site-nav">
  <div class="container">
    <div class="menu-bg-wrap">
      <div class="site-navigation">
        <a href="index.html" class="logo m-0 float-start">Property</a>

        <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
          <li class="active"><a href="{% url 'catalog:index' %}">Home</a></li>
          <li class="has-children">
            <a href="#">Catalog</a>
            <ul class="dropdown">
              <li><a href="{% url 'catalog:category_list' %}">Categories</a></li>
              <li><a href="{% url 'catalog:service_list' %}">Services</a></li>
              <li class="has-children">
                <a href="#">Dropdown</a>
                <ul class="dropdown">
                  <li><a href="#">Sub Menu One</a></li>
                  <li><a href="#">Sub Menu Two</a></li>
                  <li><a href="#">Sub Menu Three</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a href="services.html">Services</a></li>
          <li><a href="about.html">About</a></li>
          <li><a href="contact.html">Contact Us</a></li>
          <li class="has-children">
            <a href="#">{{ user }}</a>
            <ul class="dropdown">
              <li><a href="{%url 'catalog:logout' %}">Salir</a></li>
            </ul>
          </li>
        </ul>

        <a href="#" class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
          data-toggle="collapse" data-target="#main-navbar">
          <span></span>
        </a>
      </div>
    </div>
  </div>
</nav>